## Start here

In [ ]:
!pip install numpy

In [2]:

import numpy as np

In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [4]:
# Example of n-dimensional array operation in NumPy: Matrix multiplication of 2D arrays
result_numpy = np.dot(A, B)
print("NumPy result:", result_numpy)

# Equivalent operation using einsum
result_einsum = np.einsum('ij,jk->ik', A, B)
print("Einsum result:", result_einsum)

NumPy result: [[19 22]
 [43 50]]
Einsum result: [[19 22]
 [43 50]]


In [10]:
# Example 1: Transpose of a 2D array using NumPy and einsum
transpose_numpy = A.T
print("NumPy transpose of A:", transpose_numpy)

transpose_einsum = np.einsum('ij->ji', A)
print("Einsum transpose of A:", transpose_einsum)

# Example 2: Sum along specific axes of a 3D array (D is 3D)
D=np.array([[[1, 2, 3], [3, 4, 1]], [[5, 6, 3], [7, 8, 9]]])
sum_axis1_numpy = np.sum(D, axis=1)
print("NumPy sum along axis 1 of D:", sum_axis1_numpy)

sum_axis1_einsum = np.einsum('ijk->ik', D)
print("Einsum sum along axis 1 of D:", sum_axis1_einsum)

# Example 3: Outer product of two 1D arrays (a and b are 1D)
a=np.array([1, 2, 3])
b=np.array([4, 5])
outer_numpy = np.outer(a, b)
print("NumPy outer product of a and b:", outer_numpy)

outer_einsum = np.einsum('i,j->ij', a, b)
print("Einsum outer product of a and b:", outer_einsum)

# Example 4: Frobenius inner product of two matrices (A and B)
frobenius_inner_numpy = np.sum(A * B)
print("NumPy Frobenius inner product of A and B:", frobenius_inner_numpy)

frobenius_inner_einsum = np.einsum('ij,ij->', A, B)
print("Einsum Frobenius inner product of A and B:", frobenius_inner_einsum)

# Example 5: Kronecker product of two 2D arrays (A and B)
kron_numpy = np.kron(A, B)
print("NumPy Kronecker product of A and B:", kron_numpy)

kron_einsum = np.einsum('ij,kl->ikjl', A, B).reshape(A.shape[0]*B.shape[0], A.shape[1]*B.shape[1])
print("Einsum Kronecker product of A and B:", kron_einsum)

NumPy transpose of A: [[1 3]
 [2 4]]
Einsum transpose of A: [[1 3]
 [2 4]]
NumPy sum along axis 1 of D: [[ 4  6  4]
 [12 14 12]]
Einsum sum along axis 1 of D: [[ 4  6  4]
 [12 14 12]]
NumPy outer product of a and b: [[ 4  5]
 [ 8 10]
 [12 15]]
Einsum outer product of a and b: [[ 4  5]
 [ 8 10]
 [12 15]]
NumPy Frobenius inner product of A and B: 70
Einsum Frobenius inner product of A and B: 70
NumPy Kronecker product of A and B: [[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]
Einsum Kronecker product of A and B: [[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]
